name: 'PHPCBF/PHPCS M2 Github Action'
description: 'Runs PHPCBF/PHPCS against M2 code'
author: 'Ben Unsworth'
branding:
    icon: 'zap'
    color: 'green'
inputs:
    arguments:
        description: 'Arguments to add to PHPCBF CLI'
        required: true
    php_version:
        description: 'PHP version to use when installing Magento.'
        default: '7.2'
        required: false
    org_namespace:
        description: 'org module namespace app/code/{org_namepace}/'
        required: true
    full_scan:
        description: 'If set to true, phpcbf and phpcs will be ran against all PHP files in the PR. If false, this will only run against Org namepsace in app/code'
        default: 'false'
        required: false
    magento_composer_username:
        description: 'composer username for magento'
        required: true
    magento_composer_password:
        description: 'composer password for magento'
        required: true
    fe_scss_package:
        description: 'composer package for FE linting'
        required: false
outputs:
    phpcbf_output:
        description: Table of changes
    phpcbf_fixed_anything:
        description: Flag of any changes made or not
    phpcs_output:
        description: Table of Changes
    phpcs_has_errors:
        description: flag of any errors from phpcs
    phpcs_has_warnings:
        description: flag of any warnings from phpcs
    files_checked:
        description: files phpcbf and phpcs have been ran against
    gulpstyles_output:
        description: Output of gulp styles command
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.arguments }}
        - ${{ inputs.php_version }}
