# Linter Options
options:
  merge-default-rules: false

# File Ignores
files:
  ignore:
    - '/private/var/www/*/vendor/**/*.scss'
    - '/private/var/www/*/app/design/frontend/**/lib/**/*.scss'

# Rule Configuration
rules:
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - style: 'stroustrup'
      allow-single-line: false
  clean-import-paths: 2
  declarations-before-nesting: 2
  empty-line-between-blocks:
    - 0
    - include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 1
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: false
  mixins-before-declarations: 2
  nesting-depth:
    - 0
    - max-depth: 4
  no-color-keywords: 2
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-ids: 0
  no-important: 1
  no-invalid-hex: 2
  no-misspelled-properties:
    - 2
    - extra-properties:
        - 'touch-callout'
        - 'overflow-scrolling'
  no-url-domains: 1
  no-vendor-prefixes: 0
  no-warn: 1
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  pseudo-element: 2
  property-sort-order: 0
  quotes:
    - 2
    - style: 'double'
  single-line-per-selector: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-between-parens: 2
  trailing-semicolon: 2
  zero-unit: 2